### ISSUE TITLE
Unable to run on m1 mac - ModuleNotFoundError: No module named 'dask'

### ISSUE THREAD

**Issue by Avinava** [ironmussa/Optimus#1241]
**Describe the bug**

Installed the latest version of of pyoptimus[pandas], but it keeps failing  with `No module named 'dask'`

**To Reproduce**
- Started a fresh project with python 3.9
- Installed pyoptimus `pip install pyoptimus`
- try running
```
from optimus import Optimus
op = Optimus("pandas")
```

**Expected behavior**
Should just run without error

**Logs**
```
Traceback (most recent call last):
  File "/Users/user101/Workspace/Gitlab/data-toolkit/index.py", line 2, in <module>
    op = Optimus("pandas")
  File "/Users/user101/Library/Caches/pypoetry/virtualenvs/data-toolkit-4-9dHPyH-py3.9/lib/python3.9/site-packages/optimus/optimus.py", line 129, in optimus
    op = engine_function(engine, funcs)
  File "/Users/user101/Library/Caches/pypoetry/virtualenvs/data-toolkit-4-9dHPyH-py3.9/lib/python3.9/site-packages/optimus/optimus.py", line 42, in engine_function
    return func[engine](*args, **kwargs)
  File "/Users/user101/Library/Caches/pypoetry/virtualenvs/data-toolkit-4-9dHPyH-py3.9/lib/python3.9/site-packages/optimus/optimus.py", line 48, in start_pandas
    from optimus.engines.pandas.engine import PandasEngine
  File "/Users/user101/Library/Caches/pypoetry/virtualenvs/data-toolkit-4-9dHPyH-py3.9/lib/python3.9/site-packages/optimus/engines/pandas/engine.py", line 4, in <module>
    from optimus.engines.base.engine import BaseEngine
  File "/Users/user101/Library/Caches/pypoetry/virtualenvs/data-toolkit-4-9dHPyH-py3.9/lib/python3.9/site-packages/optimus/engines/base/engine.py", line 8, in <module>
    from optimus.engines.base.io.connect import Connect
  File "/Users/user101/Library/Caches/pypoetry/virtualenvs/data-toolkit-4-9dHPyH-py3.9/lib/python3.9/site-packages/optimus/engines/base/io/connect.py", line 3, in <module>
    from optimus.engines.base.dask.io.jdbc import DaskBaseJDBC
  File "/Users/user101/Library/Caches/pypoetry/virtualenvs/data-toolkit-4-9dHPyH-py3.9/lib/python3.9/site-packages/optimus/engines/base/dask/io/jdbc.py", line 4, in <module>
    from dask.dataframe import from_delayed, from_pandas
ModuleNotFoundError: No module named 'dask'

```

**Desktop (please complete the following information):**
 - OS: macOS  12.4
**Additional context**
 Also noticed since the app depends on older version of numpy installing pyoptimus[dask] keeps failing

**Comment by argenisleon** [comment]
Hi @Avinava,
This is because we are using dash to improve the data handling when connecting to databases.
We are working on using https://github.com/sfu-db/connector-x instead.
Could you please install dask?

**Comment by Avinava** [comment]
@argenisleon so shouldn't the 
`pip install pyoptimus[pandas]` ideally should include the dask engine as well ? since they are dependent. I am going to try installing dask and confirm as well

noticed the samething on vaex pip install pyoptimus[vaex]` , when running the code it says "engine.vaex" not found. (not exactly the same message, but something along the line)

**Comment by argenisleon** [comment]
@Avinava you are right. Dask should not be a [pandas] dependency. Going to work on implementing Connector-x and hope to make the transition in a couple of days.

Also, I  am going to check the vaex engine.

**Comment by argenisleon** [comment]
We are working on a deep Optimus rework. We expect to handle this for the big new release.
