### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'auth_token'

### ISSUE THREAD

**Issue by amitsood** [ironmussa/Optimus#295]
Trying to run the example code given on github but getting below error. Please advice.

Here are some of the configurations i have

************************************************************
Name: pyspark
Version: 2.3.0
Summary: Apache Spark Python API
************************************************************
OS- Mc High sierra
version: 10.13.6
************************************************************
Name: Optimus
Version: 1.0.1
************************************************************

```
import optimus as op
<IPython.core.display.HTML object>
Shell detected
Starting or getting SparkSession and SparkContext.
Traceback (most recent call last):

  File "<ipython-input-5-0f272e8fc6d6>", line 1, in <module>
    import optimus as op

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/optimus/__init__.py", line 58, in <module>
    spark = SparkSession.builder.enableHiveSupport().getOrCreate()

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/pyspark/context.py", line 343, in getOrCreate
    SparkContext(conf=conf or SparkConf())

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/pyspark/context.py", line 292, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/pyspark/java_gateway.py", line 120, in launch_gateway
    auto_convert=True))

**TypeError: __init__() got an unexpected keyword argument 'auth_token'**
```

**Comment by argenisleon** [comment]
Hi @amitsood ,

Can you create a spark session using pyspark(without optimus)?

spark = SparkSession.builder \
.master("local") \
.appName("Word Count") \
.config("spark.some.config.option", "some-value") \
.getOrCreate()

**Comment by amitsood** [comment]
Hi @argenisleon ,

I had pyspark 2.3.1 which was giving me error. I just downgraded to 2.3.0 and now i can create spark session using below code

```
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('abc').getOrCreate()

```

I get below error now

```

df = op.spark.createDataFrame(list(zip(cities, countries, population)), schema=schema)
Traceback (most recent call last):

  File "<ipython-input-4-dba3e0a207fb>", line 1, in <module>
    df = op.spark.createDataFrame(list(zip(cities, countries, population)), schema=schema)

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/pyspark/sql/session.py", line 691, in createDataFrame
    jdf = self._jsparkSession.applySchemaToPythonRDD(jrdd.rdd(), schema.json())

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/py4j/java_gateway.py", line 1160, in __call__
    answer, self.gateway_client, self.target_id, self.name)

  File "/Users/amit.sood/anaconda3/lib/python3.6/site-packages/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)

IllegalArgumentException: 'Unable to locate hive jars to connect to metastore. Please set spark.sql.hive.metastore.jars.'
```

**Comment by argenisleon** [comment]
It seems like a Spark configuration problem

Can be sure you can create a dataframe with spark

from pyspark.sql import SparkSession

```
spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.some.config.option", "some-value") \
    .getOrCreate()

sc = spark.sparkContext

spark.createDataFrame(sc.parallelize(range(1, 6)).map(lambda i: Row(single=i, double=i ** 2))).collect()
```

if not maybe your problem is related to this https://stackoverflow.com/questions/39183011/unable-to-locate-hive-jars-to-connect-to-metastore-please-set-spark-sql-hive-me

Plase let me know if that fix the problem

**Comment by argenisleon** [comment]
Hi @amitsood,

Did you solve the problem? Also, We launch version 2.0 some days ago, be sure to check it out!
