### ISSUE TITLE
Exception: Java gateway process exited before sending its port number

### ISSUE THREAD

**Issue by GildedKnight** [ironmussa/Optimus#453]
I got issue importing optimus, tried every possible solution that i could think of. 
Its been two days since i have been trying to fix the issue. Below is what i get once i try to import the optimus.

Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
[GCC 5.4.0 20160609] on linux

>>> import optimus

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.spark.SparkConf$.<init>(SparkConf.scala:714)
	at org.apache.spark.SparkConf$.<clinit>(SparkConf.scala)
	at org.apache.spark.SparkConf$$anonfun$getOption$1.apply(SparkConf.scala:388)
	at org.apache.spark.SparkConf$$anonfun$getOption$1.apply(SparkConf.scala:388)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.SparkConf.getOption(SparkConf.scala:388)
	at org.apache.spark.SparkConf.get(SparkConf.scala:250)
	at org.apache.spark.deploy.SparkHadoopUtil$.org$apache$spark$deploy$SparkHadoopUtil$$appendS3AndSparkHadoopConfigurations(SparkHadoopUtil.scala:463)
	at org.apache.spark.deploy.SparkHadoopUtil$.newConfiguration(SparkHadoopUtil.scala:436)
	at org.apache.spark.deploy.SparkSubmit$$anonfun$2.apply(SparkSubmit.scala:334)
	at org.apache.spark.deploy.SparkSubmit$$anonfun$2.apply(SparkSubmit.scala:334)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.UnknownHostException: musadiq: musadiq: No address associated with hostname
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:946)
	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:939)
	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:939)
	at org.apache.spark.util.Utils$$anonfun$localCanonicalHostName$1.apply(Utils.scala:996)
	at org.apache.spark.util.Utils$$anonfun$localCanonicalHostName$1.apply(Utils.scala:996)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.util.Utils$.localCanonicalHostName(Utils.scala:996)
	at org.apache.spark.internal.config.package$.<init>(package.scala:296)
	at org.apache.spark.internal.config.package$.<clinit>(package.scala)
	... 18 more
Caused by: java.net.UnknownHostException: musadiq: No address associated with hostname
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 27 more
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/optimus/__init__.py", line 3, in <module>
    from .optimus import *
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/optimus/optimus.py", line 11, in <module>
    from optimus.ml.models import ML
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/optimus/ml/models.py", line 13, in <module>
    spark = SparkSession.builder.getOrCreate()
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/pyspark/context.py", line 349, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/pyspark/context.py", line 298, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/musadiq/Desktop/envs/optimusEnv/lib/python3.6/site-packages/pyspark/java_gateway.py", line 94, in launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number

**Comment by argenisleon** [comment]
Hi @GildedKnight ,

Which Java version are you using? Spark works with Java 8.

**Comment by GildedKnight** [comment]
@argenisleon i am using Java 8.
**java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
**
as i mentioned i have already implemented the soultions that came from across the web and other sources, nothing seems to be working.

**Comment by argenisleon** [comment]
@GildedKnight has you tried to run Spark without Optimus. Is this and Optmius problem or and Spark problem?
Can you try this
```
from pyspark.sql import SparkSession
spark = (SparkSession.builder.getOrCreate())
```
