### ISSUE TITLE
while getting n_gram_fingerprint_cluster data frame i am getting an exception.

### ISSUE THREAD

**Issue by pallav1991** [ironmussa/Optimus#480]
I have a parquet file in HDFS and i am accessing it via optimus.load.parquet
after that i am performing keyCol.n_gram_fingerprint_cluster(df, "columnName", 3)

Please have a look at the stack trace below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dimentrix/PycharmProjects/Optimus/OptimusSpark/start.py", line 93, in root
    int(parameter.get('ngramSize')))
  File "/usr/local/lib/python3.6/dist-packages/optimus/ml/keycollision.py", line 146, in n_gram_fingerprint_cluster
    df = n_gram_fingerprint(df, col_name, n_size)
  File "/usr/local/lib/python3.6/dist-packages/optimus/ml/keycollision.py", line 112, in n_gram_fingerprint
    .cols.remove_accents(output_col)
AttributeError: 'function' object has no attribute 'split'

**Comment by argenisleon** [comment]
Hi @pallav1991, 
I could replicate the error. I expect to send a patch today.
