### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by IshanDindorkar** [ironmussa/Optimus#554]
Hi Team -

I am facing an issue with running profiler on a datetime column in my dataset. Ideally, the values in this column are in the format, for example, "Tue Apr 03 18:00:12 +0000 2012". But there are some exceptions to this rule. In some cases, the values are a long number which results in following error being thrown -

OverflowError: signed integer is greater than maximum

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:332)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:171)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:155)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:121)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:286)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.execution.python.ArrowEvalPythonExec$$anon$2.hasNext(ArrowEvalPythonExec.scala:101)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_doAggregateWithKeys_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:619)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

I am trying to delete those records which have bad datetime value and collect in a separate dataframe for analysis purpose. I would appreciate your help if you can please guide me how it can be done with the help of optimus. The library is so promising that my expectations keep on increasing, sorry for that :)

Thank you for your help.

Best-
Ishan

**Comment by argenisleon** [comment]
Hi @IshanDindorkar,

Can you help me with the exact line number that is raising the Exception?
Or much better can you paste a link to some data so I could replicate the error? Maybe via dropbox o google drive

**Comment by IshanDindorkar** [comment]
Hi @argenisleon ,

I tried capturing that part of dataset which is creating issue but it is more than 5GB. I am not able to even open that in an editor like Notepad++ or something. I created a dummy dataset that would resemble the situation and attached with this. Please let me know if it helps you in recreating the scenario.

Thank you again for your help. Much appreciated.
[error_reproduce.txt](https://github.com/ironmussa/Optimus/files/3265798/error_reproduce.txt)

**Comment by argenisleon** [comment]
To be sure. What are the columns data types? Can you run ```df.cols.dtypes()``` and paste the result here?
To handle your case I think you can use ```df.rows.drop_by_dtypes("names","int")``` to delete the that rows? Or what are you planning to do with those values?

**Comment by IshanDindorkar** [comment]
Not right now near my laptop so couldn’t run these commands. drop_by will help me serve my purpose but I wanted to copy those rows to another data frame before deleting. Is there any operation which just filters rows in data frame based on type of values in a specific column?

**Comment by argenisleon** [comment]
Sure, 
You can use ```df.rows.select_by_dtypes("your_columns","int")```

**Comment by IshanDindorkar** [comment]
Thanks!
