### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by IshanDindorkar** [ironmussa/Optimus#571]
Hi Team -

When I try to execute following command on my dataset -

op.profiler.run(checkins_df, "poiid", infer=True)

I am seeing this error -
Py4JJavaError: An error occurred while calling o804.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 43.0 failed 1 times, most recent failure: Lost task 1.0 in stage 43.0 (TID 173, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/ishan/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/home/ishan/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/ishan/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 286, in dump_stream
    for series in iterator:
  File "<string>", line 1, in <lambda>
  File "/home/ishan/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 101, in <lambda>
    return lambda *a: (verify_result_length(*a), arrow_return_type)
  File "/home/ishan/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 92, in verify_result_length
    result = f(*a)
  File "/home/ishan/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/util.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "../../../Softwares/optimuspyspark-2.2.51/optimus/functions.py", line 463, in pandas_udf_func
    return v.apply(func)
  File "/home/ishan/anaconda3/lib/python3.6/site-packages/pandas/core/series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "../../../Softwares/optimuspyspark-2.2.51/optimus/functions.py", line 448, in func
    elif str_to_array(value):
  File "../../../Softwares/optimuspyspark-2.2.51/optimus/functions.py", line 424, in str_to_array
    if isinstance(literal_eval((value.encode('ascii', 'ignore')).decode("utf-8")), (list, tuple)):
  File "/home/ishan/anaconda3/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/ishan/anaconda3/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    4d54555058856dcbb0233c6d
                           ^
SyntaxError: unexpected EOF while parsing

Could you please help!

Thanks in advance.

Best-
Ishan

P.S: Same issue I am facing with the latest version of library also.

**Comment by argenisleon** [comment]
Hi @IshanDindorkar,

Checking

**Comment by argenisleon** [comment]
@IshanDindorkar could you please install 2.2.7?. Weirdly, it's raising an exception because we caught it here https://github.com/ironmussa/Optimus/blob/master/optimus/functions.py#L426

Seems related to this https://stackoverflow.com/questions/14634925/ast-literal-eval-syntaxerror-unexpected-eof-while-parsing
