### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [ironmussa/Optimus#935]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 2.2.29. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary optimuspyspark -w /tmp/ext optimuspyspark==2.2.29
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting optimuspyspark==2.2.29
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/916/f7f0455e31b36/optimuspyspark-2.2.29.tar.gz (39.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-5c_ed5og/optimuspyspark/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-5c_ed5og/optimuspyspark/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-5c_ed5og/optimuspyspark/pip-egg-info
         cwd: /tmp/pip-wheel-5c_ed5og/optimuspyspark/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-5c_ed5og/optimuspyspark/setup.py", line 32, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by argenisleon** [comment]
Thanks @thatch for the report,

Any idea how to tackle this?

**Comment by thatch** [comment]
See PR; I can't fully test because of a bad dep on a missing version of tensorflow though.
